### ISSUE TITLE
Index Sid in SubPost table for fast retrieval for sub filter posts

### ISSUE THREAD

**Issue by axiomxd** [Phuks-co/throat#136]
Why doesn't phuks use any indexing on foreign key field like pid in subcomment table for fast queries/retrieval of data. Thanks

**Comment by Polsaker** [comment]
We do, but I've forgotten to add a migration for this after we switched from our old .sql dump to migrations for database setup

**Comment by axiomxd** [comment]
> We do, but I've forgotten to add a migration for this after we switched from our old .sql dump to migrations for database setup

Does it index parentcid in SubPostComment table? Does it require to index parentcid of  SubPostComment.  Comment retrieval is using pid of  SubPostComment. So does it need to index parentcid.

**Comment by Polsaker** [comment]
Yes.

**Comment by axiomxd** [comment]
> Yes.

Can you show the database table schema. I am testing in local development. I am confused what to index and what not to.

**Comment by Polsaker** [comment]
Just double checked and the migrations are already creating most of the required indexes. I just pushed a migration with three more indexes that shouldn't impact everyday use a lot but should help anyway.

**Comment by axiomxd** [comment]
@migrator.create_model
    class SubPostComment(pw.Model):
        cid = pw.CharField(max_length=40, primary_key=True)
        content = pw.TextField(null=True)
        lastedit = pw.DateTimeField(null=True)
        parentcid = pw.ForeignKeyField(backref='subpostcomment_set', column_name='parentcid', field='cid', model='self', null=True)
        pid = 
       
       
      

> Just double checked and the migrations are already creating most of the required indexes. I just pushed a migration with three more indexes that shouldn't impact everyday use a lot but should help anyway.

@migrator.create_model
 class SubPostComment(pw.Model):
        cid = pw.CharField(max_length=40, primary_key=True)
        parentcid = pw.ForeignKeyField(backref='subpostcomment_set', column_name='parentcid', field='cid', model='self', null=True)
        pid = pw.ForeignKeyField(backref='subpostcomment_set', column_name='pid', field='pid', model=migrator.orm['sub_post'], null=True)


Where is the indexing for pid? Does peewee migration create indexing automatically for foreignkey?

**Comment by Polsaker** [comment]
Yes
