### ISSUE TITLE
Message buttons overlap on iPhone 

### ISSUE THREAD

**Issue by happy-river** [Phuks-co/throat#154]
![33286ACA-B547-4E33-A61A-3A3E4DB4EFD1](https://user-images.githubusercontent.com/54728477/89103290-85800880-d3c5-11ea-88ad-3b49733baae9.png)

**Comment by Toxu-ru** [comment]
Perhaps   can change the css a little (`margin + display`):
https://github.com/Phuks-co/throat/blob/master/app/static/css/main.css#L1468

```
.pmessage p.container a {
    margin: 4px 4px 0 0;
    cursor: pointer;
    padding: .5em 1em;
    border-radius: 3px;
    background-color: rgba(0, 0, 0, 0.06);
    display: inline-block;
}
```
