### ISSUE TITLE
YouTube player in the sidebar doesn't seem to work

### ISSUE THREAD

**Issue by globalistas** [Phuks-co/throat#17]
Example:

https://phuks.co/s/Apple/hot

`An error occurred. Please try again later. (Playback ID: my1Hj8EOG2aF6mp_)
Learn More`

**Comment by Polsaker** [comment]
The youtube player has been unmaintained for a long time, and it had hardcoded phuks urls too. I've removed it in commit 95e76d5 until we can find a better solution
