### ISSUE TITLE
Implementing URL slugs for posts in sidebar

### ISSUE THREAD

**Issue by Toxu-ru** [Phuks-co/throat#171]
In the sidebar "Top posts in the last 24 hours" - url for posts, similarly (I think) it is necessary to do it in full paths.  We provide many options to the search engine. 

```
/@{config.site.sub_prefix}/@{post['sub']}/@{post['pid']}/@{func.slugify(post['title'])}
```

**Comment by Polsaker** [comment]
I don't think this is really necessary since we're instantly redirecting the slugless URL to the correct one immediately after

**Comment by Toxu-ru** [comment]
The search engine shows the entry point and shows the redirect in the reports. I think not to force her to do unnecessary work if the changes themselves (from our side) are minimal.

![redirect](https://user-images.githubusercontent.com/6613623/89832606-48a3d680-db68-11ea-8b12-552f80552d8e.jpg)
