### ISSUE TITLE
Invalid number of comments (Load more...)

### ISSUE THREAD

**Issue by Toxu-ru** [Phuks-co/throat#211]
Example: Load more (2 comments)
https://phuks.co/s/AskPhuks/76558/if-you-went-to-a-phuks-potluck-party-what-would-you-bring
Clicking to load more comments than stated above.

**Comment by Polsaker** [comment]
It's done this way to save us a very expensive recursive lookup to get the total number of comments

**Comment by Toxu-ru** [comment]
Maybe then it makes no sense to show the number of comments? Something general, such as "load more ...". In general, I don’t know.
