### ISSUE TITLE
Maybe should add h1 and nofollow?

### ISSUE THREAD

**Issue by Toxu-ru** [Phuks-co/throat#23]
The search engine treats any page as a document. The document must have a title and description in the meta tags. And the document itself must have a header (h1). This is not SEO, this is markup. All this should be unique for each page (document). The site consists of pages (documents).

We don’t have any of this at the moment.

It may make sense to follow their recommendations.

> Styles for text headers and H1, …, H6 tags Well-designed text headers help the user to navigate through the page and save time. It is also easier for the robot to recognize the document structure. This is why you should put the headers in the tags according to the document hierarchy.

Source Yandex (just because it is well written there, in detail): Presenting information on a site https://yandex.com/support/webmaster/recommendations/presentation.html

![oywz0t](https://user-images.githubusercontent.com/6613623/83379791-0e3df080-a3e5-11ea-99ef-d431c92823a8.jpg)

There are many sites: reddit, dev.to, stack exchange, ruqqus, discourse etc… that follow the recommendations of search engines.

Example in the photo above.

**Comment by Polsaker** [comment]
Good point. Nofollow would be a good way to discourage spammers too, since most just want more links to their sites
