### ISSUE TITLE
Incorrect notification account for some users

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#233]
This is affecting an admin and a regular user.

When there are both new comment replies and unread private messages, it multiplies the number of unread PMs with the number of comment replies and multiplies that by 2 in the total notification count. 

A thread about it: https://ovarit.com/o/Bugs/1977/incorrect-notification-count

**Comment by BoringBuffalo** [comment]
<img width="258" alt="image" src="https://user-images.githubusercontent.com/68254082/95514794-65466a00-0971-11eb-8f5f-4ea2ea587503.png">

**Comment by Polsaker** [comment]
Fixed by #236
