### ISSUE TITLE
Text that is spoiler tagged is displayed outright (not blacked out or anything) in the activity feed

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#238]

**Comment by Polsaker** [comment]
This will be a difficult one to fix. Probably the only way around is redesigning the recent activity feed to parse markdown

**Comment by BoringBuffalo** [comment]
Maybe we can replace the preview with "[contains spoiler]" instead of having the normal preview?

**Comment by Polsaker** [comment]
I found a nicer workaround
