### ISSUE TITLE
Description meta tag (unique)

### ISSUE THREAD

**Issue by Toxu-ru** [Phuks-co/throat#24]
The Description meta tag content is a source for descriptions in site snippets in the  search results. The snippet includes the text that is most informative and relevant to the search query.

The meta description should:

* **Be unique for every site page.**
* Be informative, with grammatically correct sentences, without abuse of keywords and phrases, capital letters, advertising slogans, and so on.;
* Reflect the current page status.
* **Match the document language.**
* **Differ from the content of the title element.**

Source: https://yandex.com/support/webmaster/indexing-options/description.html

This is equally suitable for all search engines.

Perhaps we should think about what should be done in this vein.

**Comment by Polsaker** [comment]
This can be done mostly in posts. There's not much data to extract anywhere else

**Comment by Toxu-ru** [comment]
Yes, that would be great!
