### ISSUE TITLE
SQLite error on recent activity query

### ISSUE THREAD

**Issue by happy-river** [Phuks-co/throat#246]
The easiest way to reproduce this is to run the tests, since they use SQLite: 

`python -m pytest`

Result: Several tests fail with "peewee.OperationalError: ORDER BY clause should come after UNION not before" at the last line of `recent_activity` in `misc.py`.

**Comment by Polsaker** [comment]
Disabled recent activity in 85b3bdd for now, since it won't be an easy fix
