### ISSUE TITLE
New posts notifications

### ISSUE THREAD

**Issue by globalistas** [Phuks-co/throat#26]
It would be nice to have a sub or site-wide Preferences option (off by default, of course) to receive notifications about new posts in subscribed subs. Separate icon from the Messages/mentions notficiations, only visible when the option is enabled.

Alternatively, maybe implement a "Mark all as read" function for both indexposts and sub/posts. This could serve as a faux "new posts" notificiation for users.

**Comment by Polsaker** [comment]
We already have a similar feature (the live feed of new posts in /all/new, enabled after ticking experimental features in the user's settings), but no mark as read feature for posts

**Comment by globalistas** [comment]
That's similar in nature, but requires you to be present on the site, to be useful. Some users may need a simple way to get up to speed on what's been happening after being away for a period of time.
