### ISSUE TITLE
Internal Server Error when using search box on /admin/postvoting/user

### ISSUE THREAD

**Issue by happy-river** [Phuks-co/throat#270]
To reproduce:
- log in as admin
- click the admin link on the sub bar
- choose Users from the side bar
- click on the votes link for one of the users
- enter something in the search box at the bottom of the sidebar and click submit

Result: `werkzeug.routing.BuildError: Could not build url for endpoint 'admin.post_voting_search' with values ['term']. Did you mean 'admin.post_search' instead?`

**Comment by Polsaker** [comment]
This was just never implemented. I'll remove that form
