### ISSUE TITLE
Make it so users who are banned in a sub can't vote in that sub

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#288]

**Comment by globalistas** [comment]
I believe this should be a sub-only feature(not site-wide), with the following options:

0 - cannot vote
1 - can vote
2 - can only upvote

**Comment by Polsaker** [comment]
imo, for consistency's sake this should be a site-wide feature

**Comment by Polsaker** [comment]
Apparently this was previously implemented (see app/misc.py:1759) but it broke when we moved bans to their own table
