### ISSUE TITLE
"make sticky" button on comments added for admins, but doesn't actually work

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#302]
If you're an admin and a mod in a sub, when you click "make sticky" on a top-level comment, it makes it sticky and distinguishes it as a mod comment (as expected)

However, if you're an admin and not a mod in a sub, the "make sticky" button shows up on your top-level comments, but doesn't do anything when clicked.

**Comment by Polsaker** [comment]
Cannot reproduce this. We do not show the `make sticky` link to admins on subs they do not mod
