### ISSUE TITLE
User flair bug: both options moderators have to pick from result in the same outcome, options in the settings are also unclear

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#304]
Moderators have two options to pick from for user flair:

"Allow users to set their own user flairs"
"Allow free-form user flairs (disables pre-defined flairs)"

Selecting the first one or selecting the second one produces the same result: users can pick from a list of moderator-made flairs, or write-in their own flair. 

Additionally, the options are pretty unclear. The options are included in a long list of unrelated sub toggle options, and it's unclear if only one of these flair options should be selected. 

It might be more clear if one option says: "Allow users to pick from moderator-created user flair options"

And the next option says: "Allow users to input their own user flair"

Turning on only the first one would turn on the ability for users to pick from the moderator created list, turning on only the second one would turn on the ability for users to input their own user flair, and turning on both options would allow them to pick from a list or write in their own.

**Comment by BoringBuffalo** [comment]
Currently user flair is "turned on" by default, but users can't change theirs by default. Mods have no way of turning flair back off entirely, so that all existing flairs stop being displayed. Any flairs that mods have assigned and that users have assigned to themselves remain after the flair options are turned off.

The default should be that user flair isn't an option and isn't displayed at all, and the display of any flair, including manually-assigned-by-mods flair, should be an option that has to be turned on.

There should be another option (on top of the above two options) in the sub settings that turns flair on at all: if this isn't selected, then the flairs that have been assigned by whatever means shouldn't be displayed.

**Comment by Polsaker** [comment]
Both options were doing the same thing because of #308. This should be fixed now.

Re: Hiding/deleting all flairs when flairs are disabled. That should either be a third option (enable/disable user flairs) or a button to clear all existing flairs.
