### ISSUE TITLE
Custom scrollbar is too thin for people to use, impossible to get rid of with additive CSS

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#305]
It would be really nice if the custom CSS for the fancy scrollbar was taken out of the default CSS. We can't override it to neutral with our additive CSS so we have to remember to take it out of the main css every time we merge.

**Comment by globalistas** [comment]
For inspiration: :)

https://github.com/globalistas/ceknito/commit/942dbd634830207c368c4e71253fd38e835b05b7
