### ISSUE TITLE
Potential copyright violation

### ISSUE THREAD

**Issue by AuroraWright** [Phuks-co/throat#324]
Just FYI, I'm no lawyer but from the looks of it this website deleted the MIT license file https://www.ovarit.com/license , which as far as I can tell is a violation.

**Comment by globalistas** [comment]
LOL that's kinda rich coming from a prolific Nintendo hacker. :D

**Comment by Polsaker** [comment]
Thanks for the report. 

Poke @happy-river, @BoringBuffalo

**Comment by Polsaker** [comment]
The issue has been resolved by the Ovarit team.
