### ISSUE TITLE
More ways to block users

### ISSUE THREAD

**Issue by faeilers** [Phuks-co/throat#325]
I can block after someone responds, but we are unable to do it from profiles, posts, or comments. It doesn't have to be all three, however I'd appreciate the option to block a user before they ever respond to me. It'd be nice if it was an option after reporting a post as well.

I'm also a little confused why even after I have blocked a user, their comments still show up on posts. I'm not sure about the overall feeds. Anyway, if you got this far, thank you for reading and all the hard work. If it isn't apparent i am just a user so i may not be using the correct terminology.

**Comment by Polsaker** [comment]
> I'm also a little confused why even after I have blocked a user, their comments still show up on posts. I'm not sure about the overall feeds. Anyway, if you got this far, thank you for reading and all the hard work. If it isn't apparent i am just a user so i may not be using the correct terminology.

The blocking function only prevents that user from sending you notifications. It doesn't affect visibility.

That's why the block button is on the messages page only, but it might be worth it to expand it so it hides/collapses posts and comments too.

**Comment by faeilers** [comment]
Thank you for clarifying. I also see some merit in both options of blocking notifications only and also collapsing posts.
