### ISSUE TITLE
Decide whether to keep moving away from Jinja2 or not

### ISSUE THREAD

**Issue by Polsaker** [Phuks-co/throat#38]
A long time ago we decided to stop using Jinja2 due to performance concerns (some templates were awfully slow) and started migrating everything to the wheezy template engine

Wheezy solved all our performance concerns and it is very fast, but it presents the following problems:

 1. It is not actively maintained: The last commit was in 2015, the project has apparently [migrated to github](https://github.com/akornatskyy/wheezy.template) recently, but it is yet to be seen if development will resume
 2. It is more prone to XSS vulnerabilities. This can be prevented by just being a bit more careful around user supplied values
 3. It has some weird quirks and bugs, like not being able to start a function with any other template tag (if, for, etc)
 4. It has a very ugly ternary syntax, which makes some conditions within translation functions way uglier than they should be

I think we should find a new template engine that is actively developed, **easier to migrate to** and fast enough for us

**Comment by ferocious-ferret** [comment]
So, you had a different implementation that was the UI but looked to be a single page app done in like Vue.js

any thought to just doing everything in Vue? Or is that implementation far enough off that looking into a different templating language seems valuable? Or do you not want to replace everything with Vue?

**Comment by Toxu-ru** [comment]
Vue.js will probably lead to additional problems. Some sites are now closed in relation to search engines, and other sites. Single-page applications do not exist for search engines, Yandex, for example, does not see them, etc.

Wheezy's main advantage is speed. It is important. I looked at the tests (unfortunately they are all from 12-13 y.).  

XSS is not a problem, you just have to be careful. As for support, it's hard to say something.

**Comment by Polsaker** [comment]
> Or is that implementation far enough off that looking into a different templating language seems valuable? Or do you not want to replace everything with Vue?

It's a bit of each.. the vue app is intended to start as a mobile only frontend and if it runs well it would progressively expand to be the main view. But it is a pretty complex undertaking currently since we only have the most basic APIs so far and the app has still a long way to go

> Single-page applications do not exist for search engines, Yandex, for example, does not see them, etc.

That is not true anymore, at least for Google. Their crawlers are perfectly capable of indexing SPAs and they do execute all the JavaScript nowadays

> XSS is not a problem, you just have to be careful. As for support, it's hard to say something.

Yeah, my main concern is upstream support with wheezy

**Comment by akornatskyy** [comment]
Gentlemen, in our open source world, [wheeze.template](https://github.com/akornatskyy/wheezy.template) is open for your contribution. Feel free report issues, suggest improvements, submit PR, etc. How does that sound to you?

**Comment by happy-river** [comment]
Back when you were having performance problems with jinja2, did you try caching the results of template rendering?  Actually I don't know if flask-caching did that then, but it does now. [Flask-Caching Documentation](https://flask-caching.readthedocs.io/en/latest/l)

**Comment by Polsaker** [comment]
I try to avoid caching remplate renders, because most of our pages are very dynamic.
Also most of our problems were around post lists and the comment view (and i'd rather keep those as fresh as possible).

The performance problems might or might have not been fixed by the jinja devs already though

**Comment by akornatskyy** [comment]
You might consider switch to browser side template rendering, using ajax call for data or relying on web sockets for near realtime user experience.

**Comment by steadyember** [comment]
The XSS vulnerabilities are a serious concern for our group. Relying on the more secure Jinja templating engine as a standard is strongly our preference. If this results in performance issues we can address them with a client-side rendering approach or use wheezy templates in only those instances as the exception rather than the rule.

**Comment by Toxu-ru** [comment]
@steadyember  There are actually no particular problems. Only a little more attention when designing templates. I will periodically (whenever possible) audit this.

**Comment by ferocious-ferret** [comment]
So, the problem is that it's hard to be careful, and if we are having more people develop Throat, then the risk goes up. I am in general skeptical of a single person reviewing everything to make sure there aren't mistakes made multiple layers deep in the stack that might cause a security vulnerability. Not because I don't think you @toxu-ru are capable, but because that puts all the security on you, and what happens if you get hit by a bus?

**Comment by Toxu-ru** [comment]
There really, everything is very insignificant.

https://github.com/Phuks-co/throat/commit/c0d27a4b719d18b2f68b2adbe3d924a553b6f872#diff-3f2ca70fd4a1c2f73686031db52c0a04R21

**Comment by Polsaker** [comment]
The quickest solution would be to find a way to make Wheezy escape by default, just like Jinja does

**Comment by akornatskyy** [comment]
Here is escape by default:

```python
from wheezy.template.comp import PY3
from wheezy.template.engine import Engine
from wheezy.template.loader import DictLoader
from wheezy.template.ext.core import CoreExtension

from wheezy.html.utils import escape_html


s = PY3 and 'str' or 'unicode'

def build_var(builder, lineno, token, value):
    assert token == 'var'
    var, _ = value
    builder.add(lineno, 'w(e(' + s + '(' + var + ')))')
    return True

class EscapeExtension(object):
    builder_rules = [
        ('var', build_var)
    ]

# setup
engine = Engine(loader=DictLoader({
  'x': """\
@require(var)
@var
"""
}), extensions=[EscapeExtension(), CoreExtension()])
engine.global_vars.update({'e': escape_html})

# test
template = engine.get_template('x')
print(template.render({
  'var': '<>'
}))
```

The idea is to override the default builder rule for `var` in custom extension... the above ignores variable filters all together, but that should be easy to add if needed.

**Comment by Polsaker** [comment]
I've been trying that locally.. It catches function calls inside of the templates too, stuff like this:

```
    @def meta_description():
        <meta name="description" content="@{config.site.lema}"/>
    @end
    @meta_description()
```
My workaround has been to change the `build_var` function to not escape anything with the `!!html` modifier:

```python
def build_var(builder, lineno, token, value):
    assert token == 'var'
    var, _ = value
    if not value[-1] or "html" not in value[-1]:
        builder.add(lineno, 'w(e(str(' + var + ')))')
    else:
        builder.add(lineno, 'w(str(' + var + '))')
    return True
```

This will require doins some major changes to our templates, since we depend on those functions returning HTML. Same thing happens with any WTForms fields

**Comment by akornatskyy** [comment]
it appears you need to be explicit either about a need to escape or the other way around (when not to escape, stating that it is HTML safe).

you might consider to analyze whenever `var` is a function call (assuming that is a template function call), e.g. ends with a closing bracket. however, the data you are rendering might use a function call as well, in this case they probably will be in-distinguishing, allowing unsafe content. thus this is not necessary a good idea. I am mentioning it here for completeness.

**Comment by Polsaker** [comment]
Yeah I ended up adding `!!html` to all function calls that really needed escaping.. it was a hassle but it'll be safer in the long run

Thank you for all the help @akornatskyy!

**Comment by akornatskyy** [comment]
I think it is reasonable to share some metrics and achieved gain, as a rational behind the move. I don't know how easy is for you to localize only template rendering part, it would good to see some numbers.

Another step in performance improvement could be in use of [preprocessor](https://wheezytemplate.readthedocs.io/en/latest/userguide.html#preprocessor). It is kind of two steps template processing based on context which effectively inlines template function calls, which are quite expensive in python. Use cases include template localization, layouts, etc... it is possible to achieve ultimately a flat template. See examples that compare [classical](https://github.com/akornatskyy/wheezy.web/tree/master/demos/template/content/templates-wheezy) vs [preprocessor](https://github.com/akornatskyy/wheezy.web/tree/master/demos/template/content/templates-preprocessor) approach.

**Comment by Polsaker** [comment]
> I think it is reasonable to share some metrics and achieved gain, as a rational behind the move. I don't know how easy is for you to localize only template rendering part, it would good to see some numbers.

I don't really have the numbers, since we did the transition last year, but it was a pretty significant difference (from ~150ms to the current 50-60ms for the frontpage)

> Another step in performance improvement could be in use of preprocessor. It is kind of two steps template processing based on context which effectively inlines template function calls, which are quite expensive in python. Use cases include template localization, layouts, etc... it is possible to achieve ultimately a flat template. See examples that compare classical vs preprocessor approach.

Oohh that sounds neat. I'm pretty happy with the current wheezy performance, but i'll do some preprocessor experiments to see if we can get any more significant gains

**Comment by Polsaker** [comment]
Closing since all the major issues with wheezy have been addressed
