### ISSUE TITLE
Bug: "Change owner of sub" on /admin/subs adds owner of sub

### ISSUE THREAD

**Issue by BoringBuffalo** [Phuks-co/throat#464]
On page /admin/subs, under heading "Change owner of sub", when you click "Transfer sub", it now adds the new person as an owner, instead of transferring ownership.

It's unclear how to remove the old owner.

**Comment by Polsaker** [comment]
This was fixed a few days ago in 0de82ec

**Comment by Polsaker** [comment]
(also, the old owner cannot be removed from the interface. only way to remove an owner is by touching the database for now)
