### ISSUE TITLE
Almost no one is using the site ... yet you discourage new people from joining by requiring an invitation code?

### ISSUE THREAD

**Issue by machineghost** [Phuks-co/throat#517]
Your site has a bunch of articles ... and no one commenting on them.  I imagine a big part of that is the fact that only people with an invite code can join.

This makes no sense to me, so I'm moving on from Phuks in my quest for a replacement for Digg ... but if you want other uses to join, maybe you shouldn't make it impossible for them to do so.

**Comment by Polsaker** [comment]
ok

**Comment by jazzakek** [comment]
lmao

**Comment by pembo210** [comment]
There is no official Throat site. Phuks is just a live demo of the Throat free software with Phuks branding. Let us know when you get your site up and running so we can come use it. Thanks.
